# This is a basic workflow to help you get started with Actions

name: Codey
on:
  pull_request:
    branches: [ "main" ]
jobs:
  caller:
    uses: snippets-n-memes/reusable-workflows/.github/workflows/codeowners-check@main
    secrets: inherit
