# This is a basic workflow to help you get started with Actions

name: Codey

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          # echo ${GITHUB_ACTOR}
          # hash=$(git log | grep commit | awk '{print $2}' | tail -n 1)
          # echo $hash
          # TEAM_SLUG=$(grep $(git diff --name-only ${hash} HEAD | awk -F '/' '{print $1}') .github/CODEOWNERS | awk -F '@' '{print $2}' | awk -F '/' '{print $2}')
          # echo $TEAM_SLUG
          echo ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF}
          git fetch origin ${GITHUB_HEAD_REF}:refs/remotes/origin/${GITHUB_HEAD_REF}
          folders=$(git diff --name-only ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF} | awk -F '/' '{print $1}')
          echo "$folders"
          for i in "$folders"; do
            TEAM_SLUG=$(grep "$i" .github/CODEOWNERS | awk -F '@' '{print $2}' | awk -F '/' '{print $2}')
            echo "$TEAM_SLUG"
            curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/orgs/${GITHUB_REPOSITORY_OWNER}/teams/${TEAM_SLUG}/memberships/${GITHUB_ACTOR}" \
              | jq -r '.state'
          done
          git diff --name-only ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF}
          # echo more
